#!/bin/sh

set -eu
set -x

# llvmorg-20.1.7
LLVM=$HOME/src/llvm-project
B=./build
J=$(($(nproc) / 2))
#CC=g++
OUT=./results
REPEAT=3

usage() {
  cat <<EOF
Usage: $(basename $0) [OPT]... CONFIG
Run LLVM tests.

Options:
  --llvm          Path to LLVM (default $LLVM).
  -j N            Build parallelism (default $J).
  -o OUTDIR       Where to store results (default $OUT).
  -n REPEAT       How many times to compile each file (default $REPEAT).
  --help, -h      Print help and exit.
  --verbose, -v   Print diagnostic info
                  (can be specified more than once).

Examples:
  \$ $(basename $0) configs.txt
EOF
  exit
}

usage_short() {
  cat >&2 <<EOF
Usage: $(basename $0) [OPT]... CONFIG
Run \`$(basename $0) -h' for more details.
EOF
  exit 1
}

me=$(basename $0)

ARGS=$(getopt -o 'hj:n:o:v' --long 'llvm:,verbose,help' -n "$(basename $0)" -- "$@")
eval set -- "$ARGS"

while true; do
  case "$1" in
    --llvm)
      LLVM="$2"
      shift 2
      ;;
    -j)
      J=$2
      shift 2
      ;;
    -o)
      OUT=$2
      shift 2
      ;;
    -n)
      REPEAT=$2
      shift 2
      ;;
    -h | --help)
      usage
      ;;
    -v | --verbose)
      V=$((V + 1))
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

test $# -eq 1 || usage_short

CONFIG="$1"

sanitize() {
  echo "$cfg" | sed -e 's/#.*//; s/^ *//; s/ *$//'
}

while read cfg; do
  cfg=$(sanitize "$cfg")
  test -n "$cfg" || continue

  name=$(echo "$cfg" | awk -F: '{print $1}')

  if test -d $OUT/$name; then
    rm -f $OUT/$name/*.log
  fi
done < "$CONFIG"

tmp=$(mktemp)

while read cfg; do
  cfg=$(sanitize "$cfg")
  test -n "$cfg" || continue

  name=$(echo "$cfg" | awk -F: '{print $1}')
  cc=$(echo "$cfg" | awk -F: '{print $2}')
  cxxflags=$(echo "$cfg" | awk -F: '{print $3}')
  ldflags=$(echo "$cfg" | awk -F: '{print $4}')
  llvmflags=$(echo "$cfg" | awk -F: '{print $5}')

  case $cc in
    gcc)
      cxx=g++
      ;;
    clang)
      cxx=clang++
      ;;
    *)
      echo "Unknown compiler: $cc"
      exit 1
  esac

  if test -z "$name"; then
    echo "Failed to parse config: $cfg"
    exit 1
  fi

  echo "Building $name..."

  rm -rf "$B"

  # We need to set CMAKE_C_COMPILER even though we don't use it
  # because Cmake needs it for config tests...
  cmake -G Ninja \
    -DCMAKE_C_COMPILER=$cc -DCMAKE_CXX_COMPILER=$cxx -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-O2 -DNDEBUG $cxxflags" -DCMAKE_EXE_LINKER_FLAGS="$ldflags" \
    $llvmflags \
    -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_ENABLE_LLD=ON -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_APPEND_VC_REV=OFF \
    -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS=clang \
    -B "$B" "$LLVM"/llvm
  cmake --build "$B" -- -j$J clang

  echo "Benchmarking $name..."
  # Preprocessed files need to be generated by hand.
  # I used the slowest files to compile: CGBuiltins, X86ISelLowering, PassBuilder.
  for f in $(dirname $0)/files/*.ii; do
    for i in $(seq 1 $REPEAT); do
      /usr/bin/time -o $tmp $B/bin/clang -O2 -w -S -o /dev/null $f
      cat $tmp >> $OUT/$name/$(basename $f).log
    done
  done
done < "$CONFIG"

rm -f $tmp
